is_debug: true
dir:
    log: /data/logs/dynamo-test
    data: /data/dynamo-test
    cache: ./cache
    template: ./templates

aws:
    profile: passport-dev
    region: cn-north-1

dynamodb:
    prefix: dynamo-test-
