imports: {  }
parameters:
    default.namespace:
        - Oasis\Mlib\
        - Vendor\DynamoTest\
services:
    app:
        properties:
            logging:
                path: '%app.dir.log%'
                level: debug
            cli:
                name: dynamo-test
                version: '0.1'
            http:
                cache_dir: '%app.dir.cache%'
                routing:
                    path: '%app.dir.config%/routes.yml'
                    namespaces:
                        - Vendor\DynamoTest\
                        - Vendor\DynamoTest\Controllers\
                twig:
                    template_dir: '%app.dir.template%'
                    globals:
                        app: '@app'
                injected_args:
                    - '@item_manager'
    item_manager:
        class: Oasis\Mlib\ODM\Dynamodb\ItemManager
        factory:
            - Vendor\DynamoTest\Database\DynamoTestDatabase
            - getItemManager
