is_debug: true
dir:
    log: /data/logs/dynamo-test
    data: /data/dynamo-test
    cache: ./cache
    template: ./templates
aws:
    profile: dynamo-test
    region: cn-north-1
dynamodb:
    prefix: dynamo-test-
